name: Undefined Tamplate
description: 우선순위가 정의되지 않은 작업을 할떄 쓰는 템플릿
title: "[undefined]: Feature Title"
labels: ["undefined"]

body:
  - type: textarea
    id: feature-contents
    attributes:
      label: Feature 설명
      description: 작업할 Feature에 대한 설명을 적어주세요.
      placeholder: ex. 타이머 화면 그리기
    validations:
      required: true
      
  - type: textarea
    id: related-view
    attributes:
      label: Related View(Optional)
      description: 작업하는 사항에 영향을 받는 View(화면)
      value: |
        - ex. HomeView
    validations:
      required: false
